"""
Describe purpose of this script here

Created: 6/18/24
"""
from subprocess import run
from typing import Mapping

from elf import read_syms


def spike_sig(elffn:str)->Mapping[int,int]:
    """
    Use spike emulator to run a test case. This will generate
    a signature which can be compared to the signature which
    is generated by the device-under-test.

    :param elffn: Name of ELF which holds the test case
    :return: Signature, in the form of a dict. The key is the address,
             and the value is the 32-bit value that was at the given
             address after the spike emulator finished.
    """
    parts=elffn.split(".")
    parts[-1]="spike"
    spikefn='.'.join(parts)
    parts[-1]="sig"
    sigfn='.'.join(parts)
    syms=read_syms(elffn)
    # Set up a run command for running the program with Spike to generate a signature.
    sigaddrs=range(syms['begin_signature'],syms['end_signature'],4)
    with open(spikefn,"wt") as ouf:
        print(f"until pc 0 {syms['exit_cleanup']:08x}",file=ouf)
        for addr in sigaddrs:
            print(f"mem {addr:08x}",file=ouf)
        print(f"q",file=ouf)
    # Run spike and get the signature
    cmdline=f"spike -d --debug-cmd={spikefn} --isa=RV32IC --pc=0x{syms['rvtest_entry_point']:08x} {elffn} 2>&1 | tee {sigfn}"
    result=run(cmdline,capture_output=True, shell=True)
    # Read signature. Signature is in the form of 32-bit memory reads, with implied
    # addresses from the begin_signature symbol up to but excluding end_signature.
    sig={}
    siglines=str(result.stdout,encoding='utf8').split("\n")
    for addr,line in zip(sigaddrs,siglines):
        sig[addr]=int(line[2:10],16)
    return sig